### PR TITLE
Add Icinga-stuff to PHP include path

### LINKED ISSUE #98: Set PHP include path & `ICINGAWEB_CONFIGDIR` explicitly
**Include path:** 
`ICINGAWEB_LIBRARY_PATH=/usr/share/icingaweb2/library`

```bash
.:/usr/share/php:$ICINGAWEB_LIBRARY_PATH:$ICINGAWEB_LIBRARY_PATH/vendor
```

**ConfigDir:** `/data/etc/icingaweb2`

### PR DESCRIPTION
**Pull request by Al2Klimov**
so that non-Icinga-stuff, e.g. PHPUnit, can reach Icinga-stuff.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Test

```bash
docker run --rm -it --entrypoint '' icinga/icingaweb2 env
```

### Before

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=48dac9acf672
TERM=xterm
HOME=/var/www
```

### After

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=7a2153ca21f6
TERM=xterm
PHP_INCLUDE_PATH=.:/usr/share/php:/usr/share/icingaweb2/library:/usr/share/icingaweb2/library/vendor
HOME=/var/www
```

**Comment by Al2Klimov** [comment]
## Test

```bash
docker run --rm -it --entrypoint '' icinga/icingaweb2 php -r 'echo ini_get("include_path");'
```

### Before

```
.:/usr/share/php
```

### After

```
.:/usr/share/php:/usr/share/icingaweb2/library:/usr/share/icingaweb2/library/vendor
```

**Review by yhabteab — COMMENTED** [review]
```bash
~/Workspace/docker-icingaweb2 (98 ✔) docker run --rm -it --entrypoint '' icinga/icingaweb2 php -r 'echo ini_get("include_path");'
Unable to find image 'icinga/icingaweb2:latest' locally
latest: Pulling from icinga/icingaweb2
b85a868b505f: Already exists 
b0bd7a9e24c4: Pull complete 
5647e980b8c6: Pull complete 
7e0bfbca9f4b: Pull complete 
cfe6b8223551: Pull complete 
359a95475ca7: Pull complete 
3c1c533318a1: Pull complete 
f61faed11b5a: Pull complete 
ffc4bc8c9dee: Pull complete 
3ec561eec184: Pull complete 
ea90a9fc993b: Pull complete 
e6866ec0105e: Pull complete 
44cb3e3c60c6: Pull complete 
8ba7eca56adc: Pull complete 
9c67f3df0416: Pull complete 
4334255e96f8: Pull complete 
2b23632b7e08: Pull complete 
27c539be78bd: Pull complete 
166f6e839a0a: Pull complete 
Digest: sha256:25317508d28ee0980478693171fe6c2a7298d5d55512638cc738490103e62a60
Status: Downloaded newer image for icinga/icingaweb2:latest
.:/usr/share/php%
```

**Comment by Al2Klimov** [comment]
Oh, I've missed a `./build.bash ../icingaweb2`.

**Review by yhabteab — APPROVED** [review]
```bash
...
Removing intermediate container 5300d1b9ca69
 ---> dd0f2389989e
Successfully built dd0f2389989e
Successfully tagged icinga/icingaweb2:latest
~/Workspace/docker-icingaweb2 (98 ✔) docker run --rm -it --entrypoint '' icinga/icingaweb2 php -r 'echo ini_get("include_path");'
.:/usr/share/php:/usr/share/icingaweb2/library:/usr/share/icingaweb2/library/vendor%
```

**Review by lippserd — APPROVED** [review]

**Pull request merged**
