### PR TITLE
Restore file removed from upstream we need

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Otherwise upcoming releases won't build.

**Comment by nilmerg** [comment]
Can't you just do `icingacli setup config webserver apache > ...`?

**Comment by Al2Klimov** [comment]
For some strange reason: no.

`[Tue Jan 17 15:11:48.901539 2023] [autoindex:error] [pid 12] [client 172.17.0.1:60946] AH01276: Cannot serve directory /usr/share/icingaweb2/public: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive`

**Comment by Al2Klimov** [comment]
Please test build.bash on your (Linux) WS.

**Comment by Al2Klimov** [comment]
But unfortunately this one isn’t an option either:

https://github.com/Icinga/icingaweb2/actions/runs/3939384017/jobs/6742426785

**Comment by Al2Klimov** [comment]
Works now.

https://github.com/Icinga/icingaweb2/actions/runs/3940915150/jobs/6744001592

**Comment by nilmerg** [comment]
Na dann :+1:

**Review by nilmerg — APPROVED** [review]
Not sure what I should review here, but here you are :man_shrugging:

**Pull request merged**
