### PR TITLE
Make logs a little more expressive

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
_bump_

**Review by N-o-X — COMMENTED** [review]
I don't really know how this improves the logs. Could you explain why you think we need this change?

**Comment by Al2Klimov** [comment]
Need? No, this is a nice to have. To clearly distinguish between Docker itself and our entrypoint.

**Review by julianbrost — COMMENTED** [review]
So the Docker entrypoint basically tries to imitate the Apache log format? So `DOCKERE` or `DCKRENT` is truncated to be the same length as `AH00163`? Do you expect anyone to parse these messages with a fixed length assumption on that token?

So I don't really see a reason for this truncation at all. But I also don't really see why the entrypoint should even try to look like Apache log.

**Comment by Al2Klimov** [comment]
IMAO every container shall log in exactly **one** format, that's already the case. This PR is just a cosmetic change. Merge it or close it.

**Pull request closed without merging**
