### PR TITLE
Comply to Icinga 2 and Icinga DB version tag scheme

### PR DESCRIPTION
**Pull request by Al2Klimov**
I.e. s/v2.10.0/2.10.0/.

### CODE REVIEW

**Review by julianbrost — COMMENTED** [review]
Won't this also strip a leading `v` from branch names? Also, why not do the same for both docker-icinga2 and docker-icingaweb2?
https://github.com/Icinga/docker-icinga2/blob/76b7f7b2e3bbad2db81588e7aa4f6118294899f4/action.bash#L42-L64

**Comment by Al2Klimov** [comment]
1. Such aren’t covered by the actions.
2. docker-icinga2 already provides the behavior #51 complies with.

**Comment by julianbrost** [comment]
1. And we just hope that it stays this way?
2. I don't really get why we should have two repos that do quite the same thing in this place but in a totally different way where one can't handle certain branch names while the other can. Why not use the same approach in both places?

**Comment by Al2Klimov** [comment]
1. Yes. For me this is fine.
2. 🤷‍♂️ #13

**Comment by julianbrost** [comment]
The more I look into this, the less I understand. So the action will right now tag any manually dispatched workflow on for example the `support/2.9` branch as `icinga/icingaweb2:2.9`, where I'd expect this tag to point to the latest 2.9.x release.

Probably it's better to have @nilmerg review this as his PR introduced the behavior that this PR will change and he's the one who will probably manually run actions and knows on which branches.

**Review by nilmerg — APPROVED** [review]
Sure, building an image for support/2.9 or any other support/release branch will mess up a version tag. But it doesn't happen automatically and never will be (as long I have a word) and I personally will also not build images for such branches.

**Pull request merged**
