### PR TITLE
Use package locales-all to speed up build times

### LINKED ISSUE #29: Use package locales-all instead of generating all locales
I'm using the time that `locale-gen` currently needs on my container build to point you to the package https://packages.debian.org/buster/locales-all that can be used to avoid this and speed up container build times. :)

### PR DESCRIPTION
**Pull request by julianbrost**
Generating all locales took so long, I even had time to create a pull request that installs the packages locales-all instead.

fixes #29

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
1. Please keep packages lists sorted.
2. Do you actually need both packages?

**Comment by julianbrost** [comment]
Not sure about 2. as `locales-all` does not depend on `locales` and [`locales` contains some files](https://packages.debian.org/buster/all/locales/filelist) that [are not in `locales-all`](https://packages.debian.org/buster/amd64/locales-all/filelist), I just kept both not to break something for sure. Probably it will be fine without the `locales` package. Would have to test that in detail though.

@nilmerg Is there anything more that would need testing than checking if switching languages works?

**Comment by nilmerg** [comment]
Nope. If a language can be chosen and is also utilized after being applied one can assume it's working.

**Comment by Al2Klimov** [comment]
I'd test 🇷🇺n or similar as it's completely non-ASCII.

**Review by Al2Klimov — APPROVED** [review]
LGTM

**Pull request merged**
